const INITIAL_TEACHERS = [
    {
        "id":  "TCH-001",
        "nameKh":  "សេម ញ៉ាន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1967-07-09",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-002",
        "nameKh":  "ជី យី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-04-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-003",
        "nameKh":  "ភួង វិន័យ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1972-05-02",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-004",
        "nameKh":  "សន សុភា",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1980-06-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-005",
        "nameKh":  "ប៊ុត បូរម្យ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1966-10-30",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-006",
        "nameKh":  "វ៉ាន់ ចាន់រិទ្ធី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1987-01-01",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-007",
        "nameKh":  "សុទ្ធ វង់",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-01-09",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-008",
        "nameKh":  "ឡឹក ហុន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1968-09-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-009",
        "nameKh":  "រឿង សុខរ័ត្ន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1983-10-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-010",
        "nameKh":  "ថាន់ រស្មី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1988-12-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "12A",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-011",
        "nameKh":  "សារ សុភានី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1975-04-11",
        "phone":  "-",
        "email":  "-",
        "subject":  "គីមីវិទ្យា",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-012",
        "nameKh":  "រឿង ទុន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1974-09-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "គីមីវិទ្យា",
        "grade":  "12B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-013",
        "nameKh":  "គន់ គិមអូន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1973-03-01",
        "phone":  "-",
        "email":  "-",
        "subject":  "គីមីវិទ្យា",
        "grade":  "10E",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-014",
        "nameKh":  "យឿន មុនីរ័ត្ន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1974-02-03",
        "phone":  "-",
        "email":  "-",
        "subject":  "គីមីវិទ្យា",
        "grade":  "11E",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-015",
        "nameKh":  "លី ដូណា",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1971-10-02",
        "phone":  "-",
        "email":  "-",
        "subject":  "គីមីវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-016",
        "nameKh":  "សារិន វ៉ាន់ឌី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1971-04-07",
        "phone":  "-",
        "email":  "-",
        "subject":  "ជីវវិទ្យា",
        "grade":  "10D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-017",
        "nameKh":  "សេង គឹមថៃ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1974-02-25",
        "phone":  "-",
        "email":  "-",
        "subject":  "ជីវវិទ្យា",
        "grade":  "11F",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-018",
        "nameKh":  "ម៉ុន សាមុត",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1995-20-10",
        "phone":  "-",
        "email":  "-",
        "subject":  "ជីវវិទ្យា",
        "grade":  "11C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-019",
        "nameKh":  "ខិម វិន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1973-08-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-020",
        "nameKh":  "ផាន់ ម៉ារ៉ាកត់",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1974-08-04",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "10B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-021",
        "nameKh":  "ប៉ូច បូផេង",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1971-04-10",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "11D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-022",
        "nameKh":  "រស់ ពិសី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1969-11-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "10F",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-023",
        "nameKh":  "អ៊ុក ភុំ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1972-07-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "សីលធម៌-ពលរដ្ឋវិទ្យា",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-024",
        "nameKh":  "គុណ សាក់ឌីន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1987-11-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "សីលធម៌-ពលរដ្ឋវិទ្យា",
        "grade":  "11A",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-025",
        "nameKh":  "សឺម សូលី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1972-06-25",
        "phone":  "-",
        "email":  "-",
        "subject":  "សីលធម៌-ពលរដ្ឋវិទ្យា",
        "grade":  "11A",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-026",
        "nameKh":  "អឿរ ចំរើនវីរៈ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1978-09-12",
        "phone":  "-",
        "email":  "-",
        "subject":  "ប្រវត្តវិទ្យា",
        "grade":  "10C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-027",
        "nameKh":  "សែម សុខលី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1985-10-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "ប្រវត្តវិទ្យា",
        "grade":  "12C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-028",
        "nameKh":  "សេង ប៊ុនរ៍ត្ន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1981-07-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "ប្រវត្តវិទ្យា",
        "grade":  "11B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-029",
        "nameKh":  "និវ ស៊ីណោយ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1988-04-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "ប្រវត្តវិទ្យា",
        "grade":  "12F",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-030",
        "nameKh":  "នេត ផល្លី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1970-02-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភូមិវិទ្យា",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-031",
        "nameKh":  "សំ បូរ័ត្ន",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1975-12-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភូមិវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-032",
        "nameKh":  "អម សុលាភ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1983-01-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភាសាបរទេស",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-033",
        "nameKh":  "អ៊ឹម ចាន់រិទ្ធ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1987-05-01",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភាសាបរទេស",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-034",
        "nameKh":  "មុត សុផាណា",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1982-01-14",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភាសាបរទេស",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-035",
        "nameKh":  "ជ ចាន់ធូ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1977-06-01",
        "phone":  "-",
        "email":  "-",
        "subject":  "ផែនដីវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-036",
        "nameKh":  "ទេព សិរីវុឌ្ឍី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1972-04-21",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "ប្រធានក្រុមបច្ចេកទេស",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-037",
        "nameKh":  "លាវ វិធូរ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1981-05-03",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "9B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-038",
        "nameKh":  "ធុយ ឈីវលាន",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1969-06-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-039",
        "nameKh":  "សូវ ស៊ុនចាយ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1973-03-15",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "8B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-040",
        "nameKh":  "វ៉ៃ វុន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1971-05-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-041",
        "nameKh":  "ប៊ុន គីមហួរ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1971-04-10",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "8D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-042",
        "nameKh":  "ជា ភក្តី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  null,
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-043",
        "nameKh":  "អ៊ិត ស្រីពៅ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1983-06-17",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-044",
        "nameKh":  "ឈឿន តុង",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1983-06-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "គណិតវិទ្យា",
        "grade":  "7B",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-045",
        "nameKh":  "ភីវ លីស",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1986-04-30",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-046",
        "nameKh":  "កង វាសនា",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1983-08-13",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "9D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-047",
        "nameKh":  "អ៊ុយ សាវឿន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-01-09",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "9C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-048",
        "nameKh":  "ប្លុង សុជាតិ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1985-07-17",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "8A",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-049",
        "nameKh":  "ប៉េង មួយឆេង",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1980-05-22",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "8C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-050",
        "nameKh":  "ឆោម វិឈាន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-05-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "7A",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-051",
        "nameKh":  "អ៊ិត ម៉ៅ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1973-04-04",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "7C",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-052",
        "nameKh":  "អេង សិលា",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1971-12-30",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "7D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-053",
        "nameKh":  "យក់ ខុល",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-05-06",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-054",
        "nameKh":  "សុង ហៃ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1972-07-18",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-055",
        "nameKh":  "ពៅ សាវី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1979-01-01",
        "phone":  "-",
        "email":  "-",
        "subject":  "រូបវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-056",
        "nameKh":  "សឺម រស្មី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1981-02-06",
        "phone":  "-",
        "email":  "-",
        "subject":  "ជីវវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-057",
        "nameKh":  "គូ ស៊ុំសោភ័ណ",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1972-04-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភូមិវិទ្យា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-058",
        "nameKh":  "សួន សោម៉ាលី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1985-12-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភាសាបរទេស",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-059",
        "nameKh":  "ម៉ៅ សុខុម",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1980-11-10",
        "phone":  "-",
        "email":  "-",
        "subject":  "ភាសាបរទេស",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-060",
        "nameKh":  "គឹម វ៉ាន់នាត",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1994-12-14",
        "phone":  "-",
        "email":  "-",
        "subject":  "កាយវប្បកម្ម-កីឡា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-061",
        "nameKh":  "ប្រាក់ បូរ៉ាត់",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1994-12-14",
        "phone":  "-",
        "email":  "-",
        "subject":  "កាយវប្បកម្ម-កីឡា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-062",
        "nameKh":  "ខេង ផល្លីន",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1972-10-07",
        "phone":  "-",
        "email":  "-",
        "subject":  "កាយវប្បកម្ម-កីឡា",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-063",
        "nameKh":  "ហម រស្មី",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1975-10-09",
        "phone":  "-",
        "email":  "-",
        "subject":  "កសិកម្ម",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-064",
        "nameKh":  "ថន សេរីរ័ត្ន",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1971-08-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-065",
        "nameKh":  "ដាំ សុធាវី",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1985-08-02",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-066",
        "nameKh":  "រាម សុបញ្ញា",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1975-04-27",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "12D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-067",
        "nameKh":  "មុត ប៊ុនធឿន",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1970-08-06",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "10D",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-068",
        "nameKh":  "សូ វណ្ណារិទ្ថ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1969-12-08",
        "phone":  "-",
        "email":  "-",
        "subject":  "កសិកម្ម",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-069",
        "nameKh":  "ទ្រី ចាន់ឡាយ",
        "nameEn":  "-",
        "gender":  "M",
        "dob":  "1984-07-05",
        "phone":  "-",
        "email":  "-",
        "subject":  "អក្សរសាស្ត្រខ្មែរ",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    },
    {
        "id":  "TCH-070",
        "nameKh":  "អ៊ឹង ណារ៉ា",
        "nameEn":  "-",
        "gender":  "F",
        "dob":  "1972-12-02",
        "phone":  "-",
        "email":  "-",
        "subject":  "កសិកម្ម",
        "grade":  "-",
        "position":  "គ្រូបង្រៀន",
        "status":  "Active",
        "joinDate":  null,
        "experienceYears":  0
    }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INITIAL_TEACHERS };
}