const INITIAL_TEACHERS = [
  {
    id: "TCH-001",
    nameKh: "សុខ ជា",
    nameEn: "Sok Chea",
    gender: "M",
    dob: "1985-05-15",
    phone: "012 345 678",
    email: "sok.chea@samdechouv.edu.kh",
    subject: "គណិតវិទ្យា",
    grade: "ថ្នាក់ទី១២",
    position: "ប្រធានក្រុមបច្ចេកទេស",
    status: "Active",
    joinDate: "2010-10-01",
    experienceYears: 16
  },
  {
    id: "TCH-002",
    nameKh: "ចាន់ ម៉ារី",
    nameEn: "Chan Mary",
    gender: "F",
    dob: "1990-08-22",
    phone: "098 765 432",
    email: "chan.mary@samdechouv.edu.kh",
    subject: "អក្សរសាស្ត្រខ្មែរ",
    grade: "ថ្នាក់ទី១១",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2014-11-15",
    experienceYears: 12
  },
  {
    id: "TCH-003",
    nameKh: "គឹម ហេង",
    nameEn: "Kim Heng",
    gender: "M",
    dob: "1988-12-05",
    phone: "017 888 999",
    email: "kim.heng@samdechouv.edu.kh",
    subject: "រូបវិទ្យា",
    grade: "ថ្នាក់ទី១២",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2012-03-20",
    experienceYears: 14
  },
  {
    id: "TCH-004",
    nameKh: "លី ស្រីនី",
    nameEn: "Ly Sreyny",
    gender: "F",
    dob: "1993-04-10",
    phone: "085 222 333",
    email: "ly.sreyny@samdechouv.edu.kh",
    subject: "គីមីវិទ្យា",
    grade: "ថ្នាក់ទី១០",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2016-09-01",
    experienceYears: 10
  },
  {
    id: "TCH-005",
    nameKh: "ម៉ៅ សុភ័ក្រ",
    nameEn: "Mao Sopheak",
    gender: "M",
    dob: "1982-11-30",
    phone: "010 444 555",
    email: "mao.sopheak@samdechouv.edu.kh",
    subject: "ជីវវិទ្យា",
    grade: "ថ្នាក់ទី១២",
    position: "អនុប្រធានក្រុមកម្រិត",
    status: "Active",
    joinDate: "2008-02-10",
    experienceYears: 18
  },
  {
    id: "TCH-006",
    nameKh: "នួន សុខា",
    nameEn: "Noun Sokha",
    gender: "F",
    dob: "1995-01-25",
    phone: "093 555 666",
    email: "noun.sokha@samdechouv.edu.kh",
    subject: "ប្រវត្តិវិទ្យា",
    grade: "ថ្នាក់ទី១១",
    position: "គ្រូបង្រៀន",
    status: "On Leave",
    joinDate: "2019-10-15",
    experienceYears: 7
  },
  {
    id: "TCH-007",
    nameKh: "សេង ពិសិដ្ឋ",
    nameEn: "Seng Piseth",
    gender: "M",
    dob: "1991-07-14",
    phone: "077 111 222",
    email: "seng.piseth@samdechouv.edu.kh",
    subject: "ភូមិវិទ្យា",
    grade: "ថ្នាក់ទី១០",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2015-05-01",
    experienceYears: 11
  },
  {
    id: "TCH-008",
    nameKh: "កែវ ណារី",
    nameEn: "Keo Nary",
    gender: "F",
    dob: "1987-03-08",
    phone: "012 999 000",
    email: "keo.nary@samdechouv.edu.kh",
    subject: "ភាសាបរទេស",
    grade: "ថ្នាក់ទី១២",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2011-09-01",
    experienceYears: 15
  },
  {
    id: "TCH-009",
    nameKh: "អ៊ុំ សុវណ្ណ",
    nameEn: "Oum Sovann",
    gender: "M",
    dob: "1994-09-18",
    phone: "096 888 777",
    email: "oum.sovann@samdechouv.edu.kh",
    subject: "ព័ត៌មានវិទ្យា",
    grade: "ថ្នាក់ទី១០",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2018-11-01",
    experienceYears: 8
  },
  {
    id: "TCH-010",
    nameKh: "សួស ធីតា",
    nameEn: "Sous Thida",
    gender: "F",
    dob: "1996-06-30",
    phone: "089 444 888",
    email: "sous.thida@samdechouv.edu.kh",
    subject: "សីលធម៌-ពលរដ្ឋវិទ្យា",
    grade: "ថ្នាក់ទី១១",
    position: "គ្រូបង្រៀន",
    status: "Active",
    joinDate: "2020-09-01",
    experienceYears: 6
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INITIAL_TEACHERS };
}
